# Generated by Django 4.1.7 on 2023-06-07 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conexion_LED',
            fields=[
                ('Id_conexion', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_led', models.CharField(max_length=255)),
                ('C_estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Emociones',
            fields=[
                ('Id_emocion', models.IntegerField(primary_key=True, serialize=False)),
                ('E_nombre', models.CharField(max_length=255)),
                ('E_coloBsc', models.CharField(max_length=255)),
                ('E_estadoA', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('Id_elemento', models.IntegerField(primary_key=True, serialize=False)),
                ('Tipo_elemn', models.CharField(max_length=255)),
                ('ElementoM', models.CharField(max_length=255)),
                ('Autor', models.CharField(max_length=255)),
                ('M_estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=15)),
                ('fechaN', models.CharField(max_length=10)),
                ('codigoVer', models.CharField(max_length=10)),
                ('img_perfil', models.CharField(max_length=255)),
                ('estado_cu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion_terapia',
            fields=[
                ('Id_sesion', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_emocion', models.IntegerField()),
                ('fecha_sesi', models.DateField()),
                ('nivel_satif', models.IntegerField()),
                ('Id_conexion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLedEmotionsPower.conexion_led')),
                ('Id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLedEmotionsPower.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='sesion_Emo',
            fields=[
                ('Id_sesion_emo', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_emocion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLedEmotionsPower.emociones')),
                ('Id_sesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLedEmotionsPower.sesion_terapia')),
            ],
        ),
        migrations.CreateModel(
            name='emo_multi',
            fields=[
                ('Id_emo_multi', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_elemento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLedEmotionsPower.multimedia')),
                ('Id_emocion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLedEmotionsPower.emociones')),
            ],
        ),
        migrations.CreateModel(
            name='Comprbante',
            fields=[
                ('Id_Comrpobante', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fecha_autu', models.CharField(max_length=10)),
                ('factura', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('Id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppLedEmotionsPower.usuario')),
            ],
        ),
    ]
