# Generated by Django 4.1.7 on 2023-05-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprbante',
            fields=[
                ('Id_Comrpobante', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fecha_autu', models.CharField(max_length=10)),
                ('factura', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('Id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appProyecto.usuario')),
            ],
        ),
    ]
