# Generated by Django 4.1.7 on 2023-05-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto', '0002_comprbante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conexion_LED',
            fields=[
                ('Id_conexion', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_led', models.CharField(max_length=255)),
                ('C_estado', models.BooleanField()),
            ],
        ),
    ]
