# Generated by Django 4.1.7 on 2023-05-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto', '0005_sesion_emo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emociones',
            fields=[
                ('Id_emocion', models.IntegerField(primary_key=True, serialize=False)),
                ('E_nombre', models.CharField(max_length=255)),
                ('E_coloBsc', models.CharField(max_length=255)),
                ('E_estadoA', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='sesion_emo',
            name='Id_emocion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appProyecto.emociones'),
        ),
    ]
