# Generated by Django 4.1.7 on 2023-05-19 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto', '0006_emociones_alter_sesion_emo_id_emocion'),
    ]

    operations = [
        migrations.CreateModel(
            name='emo_multi',
            fields=[
                ('Id_emo_multi', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_elemento', models.CharField(max_length=255)),
                ('Id_emocion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appProyecto.emociones')),
            ],
        ),
    ]
