# Generated by Django 4.1.7 on 2023-05-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto', '0007_emo_multi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('Id_elemento', models.IntegerField(primary_key=True, serialize=False)),
                ('Tipo_elemn', models.CharField(max_length=255)),
                ('ElementoM', models.CharField(max_length=255)),
                ('Autor', models.CharField(max_length=255)),
                ('M_estado', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='emo_multi',
            name='Id_elemento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appProyecto.multimedia'),
        ),
    ]
